// This file is auto-generated by the Supabase CLI and provides type safety for your database tables.
// It should be updated whenever your database schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          updated_at?: string;
          username?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          role: 'admin' | 'instructor' | 'user';
          email?: string | null;
        };
        Insert: {
          id: string;
          updated_at?: string;
          username?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: 'admin' | 'instructor' | 'user';
          email?: string | null;
        };
        Update: {
          id?: string;
          updated_at?: string;
          username?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: 'admin' | 'instructor' | 'user';
          email?: string | null;
        };
      };
      sessions: {
        Row: {
          id: number;
          created_at: string;
          updated_at: string;
          title: string;
          description: string | null;
          type: 'class' | 'event' | 'other';
          date: string;
          time: string;
          location: string;
          instructor: string;
          capacity: number;
          program: string;
          year: string;
          section: string;
        };
        Insert: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          title: string;
          description?: string | null;
          type: 'class' | 'event' | 'other';
          date: string;
          time: string;
          location: string;
          instructor: string;
          capacity: number;
          program: string;
          year: string;
          section: string;
        };
        Update: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          title?: string;
          description?: string | null;
          type?: 'class' | 'event' | 'other';
          date?: string;
          time?: string;
          location?: string;
          instructor?: string;
          capacity?: number;
          program?: string;
          year?: string;
          section?: string;
        };
      };
      students: {
        Row: {
          id: number;
          created_at: string;
          updated_at: string;
          student_id: string;
          firstname: string;
          surname: string;
          program: string;
          year: string;
          section: string;
          signature_url: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          student_id: string;
          firstname: string;
          surname: string;
          program: string;
          year: string;
          section: string;
          signature_url?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          student_id?: string;
          firstname?: string;
          surname?: string;
          program?: string;
          year?: string;
          section?: string;
          signature_url?: string | null;
        };
      };
      attendance: {
        Row: {
          id: number;
          created_at: string;
          updated_at: string;
          session_id: number;
          student_id: number;
          status: 'present' | 'absent' | 'late' | 'excused';
          time_in: string | null;
          time_out: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          session_id: number;
          student_id: number;
          status: 'present' | 'absent' | 'late' | 'excused';
          time_in?: string | null;
          time_out?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          session_id?: number;
          student_id?: number;
          status?: 'present' | 'absent' | 'late' | 'excused';
          time_in?: string | null;
          time_out?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Re-export types for easier access
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Session = Database['public']['Tables']['sessions']['Row'];
export type Student = Database['public']['Tables']['students']['Row'];
export type Attendance = Database['public']['Tables']['attendance']['Row'];
