// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjqvyoujvjzodtwlqlal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcXZ5b3Vqdmp6b2R0d2xxbGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjMyMDQsImV4cCI6MjA2OTg5OTIwNH0.BzQ0wpsO2NEXRXxe66F7J2aeSEoKossrIgUyCo7tpJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});